##################################################################################################应用程序端口
server:
  port: 8181
################## 项目基本配置 ################
  servlet:
    # 项目访问路径前缀
    context-path: /book_manager

##################################################################################################设置数据源
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://42.192.84.4:3306/book-store?useSSL=false&characterEncoding=UTF8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  # 注册到Eureka的服务名
  application:
    name: 图书管理模块

  #######设置邮箱
  mail:
    host: smtp.qq.com
    username: 286142025@qq.com
    password: fvnjdblkdruidcgj
    default-encoding: utf-8
    properties.mail.smto.ssl.enable: true




##################################################################################################swagger2设置
swagger:
  #标题
  title: A_sheng旧书交易系统-图书管理系统
  #说明
  description: 后台调试API专用界面
  #版本
  version: 1.0.RELEASE
  #许可证
  license: Apache License, Version 2.0
  #许可证链接
  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  #\u670D\u52A1\u6761\u6B3EURL
  terms-of-service-url: https://github.com/Jingjiasheng/book_store
  #维护人员信息
  contact:
    #维护人员邮箱
    email: j_jiasheng@qq.com
    #维护人姓名
    name: J_jiasheng
    #维护人信息连接
    url: https://github.com/Jingjiasheng/book_store
  #swagger基础包
  base-package: com.asheng.book_store.controller
  #默认访问url
  base-path: /**

################################################################################################设置mybatis的驼峰命名以及xml文件的映射位置上
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml


################## Eureka配置 ################
eureka:
  client:
    service-url:
      defaultZone: http://42.192.84.4:8761/eureka,http://42.192.84.4:8760/eureka