##################################################################################################应用程序端口
server:
  port: 8181
################## 项目基本配置 ################
  servlet:
    # 项目访问路径前缀
    context-path: /book_manager

##################################################################################################设置数据源
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://42.192.84.4:3306/book_store?useSSL=false&characterEncoding=UTF8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      #设置初始化连接数大小，最小，最大
      initial-size: 20
      min-idle: 1
      max-active: 40
      #设置等待超时时间
      max-wait: 60000
      #配置数据库空闲连接检测间隔时间
      time-between-eviction-runs-millis: 60000
      #配置一个连接在连接池中最小的生存时间
      min-evictable-idle-time-millis: 300000

      #未知项
      validation-query: select 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true

      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      #'wall'用于防火墙，SpringBoot中没有log4j，我改成了log4j2
      filters: stat,wall,log4j2

      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

      # 配置StatFilter
      web-stat-filter:
        #默认为false，设置为true启动
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #配置StatViewServlet
      stat-view-servlet:

        url-pattern: "/druid/*"
        #允许那些ip
        #allow: 127.0.0.1
        login-username: admin
        login-password: 123456
        #禁止那些ip
        #deny: 192.168.1.102
        #是否可以重置
        reset-enable: true
        #启用
        enabled: true
  # 注册到Eureka的服务名
  application:
    name: 图书管理模块

  #######设置邮箱
  mail:
    host: smtp.qq.com
    username: 286142025@qq.com
    password: fvnjdblkdruidcgj
    default-encoding: utf-8
    properties.mail.smto.ssl.enable: true




##################################################################################################swagger2设置
swagger:
  #标题
  title: A_sheng旧书交易系统-图书管理系统
  #说明
  description: 后台调试API专用界面
  #版本
  version: 1.0.RELEASE
  #许可证
  license: Apache License, Version 2.0
  #许可证链接
  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  #\u670D\u52A1\u6761\u6B3EURL
  terms-of-service-url: https://github.com/Jingjiasheng/book_store
  #维护人员信息
  contact:
    #维护人员邮箱
    email: j_jiasheng@qq.com
    #维护人姓名
    name: J_jiasheng
    #维护人信息连接
    url: https://github.com/Jingjiasheng/book_store
  #swagger基础包
  base-package: com.asheng.book_store.controller
  #默认访问url
  base-path: /**

################################################################################################设置mybatis的驼峰命名以及xml文件的映射位置上
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml


################## Eureka配置 ################
eureka:
  client:
    service-url:
      defaultZone: http://42.192.84.4:8761/eureka,http://42.192.84.4:8760/eureka